# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# 1. Código del Horno
"""

import numpy as np
import matplotlib.pyplot as plt

#---------------Parámetros que el usuario va a ingresar---------------#
#definimos las variables que seran dadas por el ususario

  #Ingresa la temperatura a la que el horno estara
T_ambiente = float(input("Ingrese la temperatura del horno (°C): "))

  #Ingresa la temperatura a la que el alimento se encuentra al empezar la cocción
T_inicial = float(input("Ingrese la temperatura inicial del alimento (°C): "))

  #Ingresa la temperatura que desea que alcance el alimento
T_deseada = float(input("Ingrese la temperatura interna deseada del alimento (°C): "))

# Constante de transferencia de calor
k = 0.1

# Definimos el tiempo
tiempo = np.linspace(0, 60, 500)  # 60 minutos en 500 puntos

# Ecuación de temperatura en el tiempo
T = T_ambiente - (T_ambiente - T_inicial) * np.exp(-k * tiempo)

# Calcula el tiempo aproximado en que la temperatura del alimento es la deseada
tiempo_calentamiento = tiempo[np.argmax(T >= T_deseada)]

# Gráfico
plt.plot(tiempo, T, label="Temperatura del alimento")
plt.axhline(T_deseada, color='r', linestyle="--", label="Temperatura deseada")
plt.axvline(tiempo_calentamiento, color='g', linestyle="--", label=f"Tiempo de calentamiento ~ {tiempo_calentamiento:.1f} min")
plt.xlabel("Tiempo (minutos)")
plt.ylabel("Temperatura (°C)")
plt.title("Cambio de temperatura en el horno")
plt.legend()
plt.grid(True)
plt.show()

print(f"Tiempo aproximado para alcanzar la temperatura deseada: {tiempo_calentamiento:.1f} minutos")